name: CI CACHE TEST

on:
  push:
    branches: [ review ]

jobs:
  cache-and-repo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default
        uses: actions/checkout@v2

      - name: Checkout the Ruby Storage Cache 
        uses: actions/checkout@v2
        with:
          repository: kentonshade/ruby-storage-cache
          path: storage-cache
          ref: master

      - name: Review the workspace
        run: |
          cd ${GITHUB_WORKSPACE}
          ls -la
          du -sh storage-cache/
          cd storage-cache
          cd gha
          ls -la

      - name: Commands 1 ## 
        uses: docker://kentonshade/newrelic-ruby:bionic-runner-2.2.0
        with:
          command: |
            ## su - gha  ## Interestingly, cannot change the user during the build - run sudo as a user and test
            cd ${GITHUB_WORKSPACE}
            ls -la 
            cd /home/gha
            ls -la
            HOME=/home/gha
            export PATH="$HOME/bin:$PATH"
            export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
            export PATH="$HOME/.rbenv/shims:$PATH"
            export PATH="$HOME/.rbenv/bin:$PATH"
            rbenv versions
            whoami
            echo $PATH
            printenv