name: CI POC1

on: ## Event that triggers the workflow - https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  push: 
    branches: [ review ]
  # pull_request:  ## nothing configured here
  # schedule:  ## Scheduled run of build per syntax below:
  #   - cron:  '0 9 * * *'  ## min, hour, day, month, day of week - this should run every day at 9am - confirm...

jobs:  ## Rememeber run in parallel by default - see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
  check-local-ruby :  ## Job ID, no job name designated
    env:
      RBENV: /root/.rbenv/bin/rbenv
    runs-on: ubuntu-latest
    container:
      image: kentonshade/mycirrus_1:nr-multiverse-sq1 ## changing image
      credentials:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: set paths  ## add everything here to script files.
        run: |
          echo "/root/.rbenv/bin" >> $GITHUB_PATH
          echo "/root/.rbenv/plugins/ruby-build/bin" >> $GITHUB_PATH


      - name: 01 Source required files  ## add everything here to script files.
        run: .github/workflows/scripts/source-and-env-variables.sh  

      - name: 02 set path variables ## need to add path variables
        run: printenv

      - name: 02 Command check ## need to add path variables
        run: |
          ls -la && (cd /3.0.0 && rbenv local)
          (cd /3.0.0 && gem list --local)  ## checking command without rbenv exec

      - name: 03 list gems  ## need to add path avariables
        run: |
          (cd /2.4.10 && rbenv local)
          #(cd /2.4.10 && rbenv exec gem list --local)

