name: CI POC1

on: ## Event that triggers the workflow - https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  push: 
    branches: [ review ]
  # pull_request:  ## nothing configured here
  # schedule:  ## Scheduled run of build per syntax below:
  #   - cron:  '0 9 * * *'  ## min, hour, day, month, day of week - this should run every day at 9am - confirm...

jobs:  ## Rememeber run in parallel by default - see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
  check-local-ruby :  ## Job ID, no job name designated
    runs-on: ubuntu-latest
    container:
      image: kentonshade/mycirrus_1:nr-multiverse
      credentials:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: 01 Source required files  ## add everything here to script files.
        run: .github/workflows/scripts/source-and-env-variables.sh  

      - name: 02 set path variables ## need to add path variables
        run: printenv

      - name: 02 Command check ## need to add path variables
        run: ls -la && (cd /3.0.0 && ${RBENV_BIN} local)

      - name: 03 list gems  ## need to add path avariables
        run: ls -la && (cd /3.0.0 && RBENV_VERSION=3.0.0 ${RBENV_BIN}exec gem list --local)

